name: Welcome Anna

on:
  push:
    branches:
      - main

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Welcome message 🎉
        run: |
          echo "🌟🎉🎊✨ WELCOME ANNA! ✨🎊🎉🌟"
          echo ""
          echo "🥳🚀 You have modified these files in that commit:"
          echo ""

          git diff-tree --no-commit-id --name-status -r "${{ github.sha }}"
